# Generated by Django 3.1.1 on 2020-09-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0002_auto_20200928_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='0', upload_to='images'),
        ),
    ]
