# Generated by Django 3.1.1 on 2020-09-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0004_auto_20200928_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
