# Generated by Django 3.1.1 on 2020-09-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_Of_Guests',
            new_name='number_of_guests',
        ),
    ]
