# Generated by Django 3.1.1 on 2020-09-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0007_auto_20200929_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.CharField(default='', max_length=100),
        ),
    ]
